name: Check Python Versions

on:
  workflow_dispatch:
  push:
    paths:
      - '**/requirements.txt'  # Dependency file
      - '**/setup.py'          # Setup script
      - '.github/workflows/pyversions.yml' #This file
permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"] #, "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'                       # enable built-in cache
            cache-dependency-path: backend/requirements.txt
    
      - name: Resolve dependencies only
        run: |
            cd backend
            python -m pip install --upgrade pip
            pip install -U setuptools wheel
            # Resolve requirements and editable package - no wheels pulled, no files installed
            python -m pip install --dry-run -e . -r requirements.txt
          

