name: Check Python Versions

on:
  workflow_dispatch:
  push:
    paths:
      - '**/requirements.txt'  # Dependency file
      - '**/setup.py'          # Setup script
      - '.github/workflows/pyversions.yml' #This file
permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"] #, "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'                       # enable built-in cache
            cache-dependency-path: backend/requirements.txt
    
      - name: Resolve direct-URL deps
        run: |
            cd backend
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install --dry-run -r requirements.txt
    
      - name: Resolve editable package (no deps)
        run: |
            cd backend
            python -m pip install --dry-run -e . --no-deps
